convert to python 3
csivanich/dux pull request #2
Opened 2020-05-14 02:52 UTC by fawaf

2020-05-18 20:22 UTC, csivanich commented
Will test today, but looks like it'll work.

2020-05-18 20:29 UTC, csivanich requested changes

2020-05-18 20:29 UTC, csivanich commented on dux.py
> +#!/usr/bin/env python
```suggestion
#!/usr/bin/env python3
```
```
 c@mu ~: which python                                                    20:28:45 99% (2.4.0p0)
/usr/bin/python
 c@mu ~: python --version                                                20:28:47 99% (2.4.0p0)
Python 2.7.17
```

2020-06-30 01:40 UTC, fawaf commented
poketh

2021-09-13 19:20 UTC, fawaf commented
poketh @csivanich

2022-02-08 20:32 UTC, fawaf commented
poke @csivanich

2023-04-18 23:48 UTC, fawaf commented
@csivanich poketh

2023-05-26 07:31 UTC, closed without merging